interface DataListData {
	name: string;
}

export const dataListData: DataListData[] = [
	{ name: 'Alejandro Aparicio' },
	{ name: 'Alejandro Mazo' },
	{ name: 'Alexia Marx' },
	{ name: 'Ana Cristina Montoya' },
	{ name: 'Ana María Estrada' },
	{ name: 'Andrés Berrío' },
	{ name: 'Andrés González' },
	{ name: 'Andrés López' },
	{ name: 'Andrés Peña' },
	{ name: 'Ángela García' },
	{ name: 'Armando Montenegro' },
	{ name: 'Camilo Aristizábal' },
	{ name: 'Camilo López' },
	{ name: 'Carlos Ochoa' },
	{ name: 'Carolina Gómez' },
	{ name: 'Catalina Arango' },
	{ name: 'Christian Barreto' },
	{ name: 'Cristian Quintero' },
	{ name: 'Daniel Bradford' },
	{ name: 'Daniel Guardiola' },
	{ name: 'Daniel Roa' },
	{ name: 'Daniela Salazar' },
	{ name: 'David Bedoya' },
	{ name: 'Diana Sánchez' },
	{ name: 'Diana Silvana Hernández' },
	{ name: 'Edgar Ruiz' },
	{ name: 'Esteban García' },
	{ name: 'Esteban Jaramillo' },
	{ name: 'Esteban Zuluaga' },
	{ name: 'Felipe Peláez' },
	{ name: 'Germán Abella' },
	{ name: 'Gonzalo Toro' },
	{ name: 'Gustavo Ortiz' },
	{ name: 'Hania Cárdenas' },
	{ name: 'John López' },
	{ name: 'Jorge Lagos' },
	{ name: 'Jorge Llano' },
	{ name: 'José Joaquín Prieto' },
	{ name: 'Juan Camilo Velásquez' },
	{ name: 'Juan Felipe Plata' },
	{ name: 'Juan Felipe Valencia' },
	{ name: 'Juan Manuel Velasco' },
	{ name: 'Juan Rafael Pérez' },
	{ name: 'Juliana Barrero' },
	{ name: 'Juliana Duque' },
	{ name: 'Juliana Pareja' },
	{ name: 'Juliana Rodríguez' },
	{ name: 'Laura Arciniegas' },
	{ name: 'Leonardo García' },
	{ name: 'Liliana Escobar' },
	{ name: 'Lina Uribe' },
	{ name: 'Luis Echeverri' },
	{ name: 'Luisa González' },
	{ name: 'Luisa Plazas' },
	{ name: 'Mabel Moreno' },
	{ name: 'Marcela Echeverria' },
	{ name: 'Marcos Saldarriaga' },
	{ name: 'María Clara Ojalvo' },
	{ name: 'Mateo de Castro' },
	{ name: 'Munir Jalil' },
	{ name: 'Natalia Torres' },
	{ name: 'Natalia Zuluaga' },
	{ name: 'Nicolás Ramírez' },
	{ name: 'Olga Lucía Vargas' },
	{ name: 'Olga Ochoa' },
	{ name: 'Patricia Amado' },
	{ name: 'Patricia Baena' },
	{ name: 'Roberto Murcia' },
	{ name: 'Roberto Páez' },
	{ name: 'Santiago Pardo' },
	{ name: 'Sebastián Arango' },
	{ name: 'Sergio Guzmán' },
	{ name: 'Verónica Vélez' },
	{ name: 'Viviana González' },
	{ name: 'Willy Castaño' },
]